'use client';
// Generated by scripts/dc-to-jsx.mjs.
import dynamic from 'next/dynamic';

export const SCREENS = {
  "/admin": dynamic(() => import('./AdminConsole'), { ssr: false }),
  "/attend": dynamic(() => import('./AttendAndMyExpo'), { ssr: false }),
  "/connect": dynamic(() => import('./Connect'), { ssr: false }),
  "/design-system": dynamic(() => import('./DesignSystem'), { ssr: false }),
  "/exhibit": dynamic(() => import('./Exhibit'), { ssr: false }),
  "/portal": dynamic(() => import('./ExhibitorPortal'), { ssr: false }),
  "/explore": dynamic(() => import('./Hall2DigitalTwin'), { ssr: false }),
  "/": dynamic(() => import('./Home'), { ssr: false }),
  "/mobile": dynamic(() => import('./MobileApp'), { ssr: false }),
  "/programme": dynamic(() => import('./ProgrammeAndWatch'), { ssr: false }),
  "/zones": dynamic(() => import('./ZoneExperiences'), { ssr: false }),
};
